export const RESET_COUNTER = "RESET_COUNTER";
export const HANDLE_USER_CODE_INPUT = "HANDLE_USER_CODE_INPUT";
export const SUBMIT_USER_CODE_INPUT = "SUBMIT_USER_CODE_INPUT";
export const CHANGE_LETTER_PROGRESSION_MODE = "CHANGE_LETTER_PROGRESSION_MODE";